version: 2
updates:
  # Enable version updates for gomod
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for github-actions
  # - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
  #    directory: "/"
  #    schedule:
  #    interval: "weekly"
