name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      consul:
        image: consul:1.15.4
        env:
          CONSUL_BIND_INTERFACE: eth0
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        WIKIA_ENVIRONMENT: testing
      run: go test -v ./...
